package be.intecbrussel.taskmanager.model;

public enum JobTitle {
    FULLSTACK_DEVELOPER, BACKEND_DEVELOPER, FRONTEND_DEVELOPER, UI_UX_DESIGNER,
    TEST_AUTOMATION_ENGINEER, DEVOPS, BUSINESS_ANALYST
}
